default:
    indexer:
# Root directory from which to index
        root: "C:"
    database:
# Server hostname of the database
        server: localhost
# Port number of the database (default: 27017)
        port: 27017
# Buffer threshold for database write operations list (default: 2048)
        buffer: 2048
# Leave as blank, unless you want to dump to the specified JSON file instead of to database
        debug_override: ""
# Verbose logging output
    verbose: false
